class AppLocalizations {
  static const String fallbackLanguage = 'English';

  static const List<String> supportedLanguages = <String>[
    'English',
    'Telugu',
    'Hindi',
    'Tamil',
    'Malayalam',
    'Kannada',
    'Marathi',
    'Gujarati',
    'Punjabi',
    'Bengali',
  ];

  static const Map<String, Map<String, String>>
  _localizedValues = <String, Map<String, String>>{
    'English': <String, String>{
      'connect_report_resolve': 'Connect. Report. Resolve.',
      'heading_line_1': 'Our Leader.',
      'heading_line_2': 'Our Community.',
      'heading_line_3': 'Our Future.',
      'get_started': 'Get Started',
      'login': 'Login',
      'choose_role': 'Choose your role',
      'citizen': 'Citizen',
      'citizen_subtitle': 'Report Issues, Track Updates',
      'leader': 'Leader',
      'leader_subtitle': 'Follow Leaders, View Dashboard',
      'continue': 'Continue',
      'email': 'Email',
      'password': 'Password',
      'required': 'Required',
      'login_failed': 'Login failed',
      'role_redirect_note': 'Role-based routing will redirect after sign-in.',
      'language_changed': 'Language changed',
    },
    'Telugu': <String, String>{
      'connect_report_resolve': 'కనెక్ట్ అవ్వండి. నివేదించండి. పరిష్కరించండి.',
      'heading_line_1': 'మన నాయకుడు.',
      'heading_line_2': 'మన సమాజం.',
      'heading_line_3': 'మన భవిష్యత్తు.',
      'get_started': 'ప్రారంభించండి',
      'login': 'లాగిన్',
      'choose_role': 'మీ పాత్రను ఎంచుకోండి',
      'citizen': 'పౌరుడు',
      'citizen_subtitle': 'సమస్యలను నివేదించండి, నవీకరణలను ట్రాక్ చేయండి',
      'leader': 'నేత',
      'leader_subtitle': 'నేతలను ఫాలో అవండి, డ్యాష్‌బోర్డ్ చూడండి',
      'continue': 'కొనసాగించండి',
      'email': 'ఇమెయిల్',
      'password': 'పాస్‌వర్డ్',
      'required': 'అవసరం',
      'login_failed': 'లాగిన్ విఫలమైంది',
      'role_redirect_note':
          'సైన్-ఇన్ తర్వాత పాత్ర ఆధారంగా దారి మళ్లింపు జరుగుతుంది.',
      'language_changed': 'భాష మార్చబడింది',
    },
    'Hindi': <String, String>{
      'connect_report_resolve': 'जुड़ें। रिपोर्ट करें। समाधान पाएं।',
      'heading_line_1': 'हमारे नेता।',
      'heading_line_2': 'हमारा समुदाय।',
      'heading_line_3': 'हमारा भविष्य।',
      'get_started': 'शुरू करें',
      'login': 'लॉगिन',
      'choose_role': 'अपनी भूमिका चुनें',
      'citizen': 'नागरिक',
      'citizen_subtitle': 'समस्या रिपोर्ट करें, अपडेट ट्रैक करें',
      'leader': 'नेता',
      'leader_subtitle': 'नेताओं को फॉलो करें, डैशबोर्ड देखें',
      'continue': 'आगे बढ़ें',
      'email': 'ईमेल',
      'password': 'पासवर्ड',
      'required': 'आवश्यक',
      'login_failed': 'लॉगिन असफल',
      'role_redirect_note':
          'साइन-इन के बाद भूमिका के हिसाब से रीडायरेक्ट होगा।',
      'language_changed': 'भाषा बदल दी गई',
    },
    'Tamil': <String, String>{
      'connect_report_resolve':
          'இணையுங்கள். புகார் செய்யுங்கள். தீர்வு பெறுங்கள்.',
      'heading_line_1': 'எங்கள் தலைவர்.',
      'heading_line_2': 'எங்கள் சமூகம.',
      'heading_line_3': 'எங்கள் எதிர்காலம்.',
      'get_started': 'தொடங்குங்கள்',
      'login': 'உள்நுழைவு',
      'choose_role': 'உங்கள் பங்கையைத் தேர்வு செய்யுங்கள்',
      'citizen': 'குடிமகன்',
      'citizen_subtitle':
          'சிக்கல்களை பதிவு செய்யுங்கள், புதுப்பிப்புகளை கண்காணிக்குங்கள்',
      'leader': 'தலைவர்',
      'leader_subtitle': 'தலைவர்களை பின்தொடருங்கள், டாஷ்போர்டை பாருங்கள்',
      'continue': 'தொடரவும்',
      'email': 'மின்னஞ்சல்',
      'password': 'கடவுச்சொல்',
      'required': 'தேவையானது',
      'login_failed': 'உள்நுழைவு தோல்வி',
      'role_redirect_note': 'உள்நுழைந்த பிறகு பங்கு அடிப்படையில் மாற்றப்படும்.',
      'language_changed': 'மொழி மாற்றப்பட்டது',
    },
    'Malayalam': <String, String>{
      'connect_report_resolve':
          'ബന്ധപ്പെടുക. റിപ്പോർട്ട് ചെയ്യുക. പരിഹാരം നേടുക.',
      'heading_line_1': 'നമ്മുടെ നേതാവ്.',
      'heading_line_2': 'നമ്മുടെ സമൂഹം.',
      'heading_line_3': 'നമ്മുടെ ഭാവി.',
      'get_started': 'തുടങ്ങുക',
      'login': 'ലോഗിൻ',
      'choose_role': 'നിങ്ങളുടെ പങ്ക് തിരഞ്ഞെടുക്കുക',
      'citizen': 'പൗരൻ',
      'citizen_subtitle':
          'പ്രശ്നങ്ങൾ റിപ്പോർട്ട് ചെയ്യുക, അപ്ഡേറ്റുകൾ പിന്തുടരുക',
      'leader': 'നേതാവ്',
      'leader_subtitle': 'നേതാക്കളെ പിന്തുടരുക, ഡാഷ്ബോർഡ് കാണുക',
      'continue': 'തുടരുക',
      'email': 'ഇമെയിൽ',
      'password': 'പാസ്‌വേഡ്',
      'required': 'ആവശ്യമാണ്',
      'login_failed': 'ലോഗിൻ പരാജയപ്പെട്ടു',
      'role_redirect_note':
          'സൈൻ-ഇൻ കഴിഞ്ഞാൽ പങ്കിന്റെ അടിസ്ഥാനത്തിൽ റീഡയറക്ട് ചെയ്യും.',
      'language_changed': 'ഭാഷ മാറ്റി',
    },
    'Kannada': <String, String>{
      'connect_report_resolve': 'ಸಂಪರ್ಕಿಸಿ. ವರದಿ ಮಾಡಿ. ಪರಿಹಾರ ಪಡೆಯಿರಿ.',
      'heading_line_1': 'ನಮ್ಮ ನಾಯಕ.',
      'heading_line_2': 'ನಮ್ಮ ಸಮುದಾಯ.',
      'heading_line_3': 'ನಮ್ಮ ಭವಿಷ್ಯ.',
      'get_started': 'ಪ್ರಾರಂಭಿಸಿ',
      'login': 'ಲಾಗಿನ್',
      'choose_role': 'ನಿಮ್ಮ ಪಾತ್ರವನ್ನು ಆಯ್ಕೆಮಾಡಿ',
      'citizen': 'ನಾಗರಿಕ',
      'citizen_subtitle':
          'ಸಮಸ್ಯೆಯನ್ನು ವರದಿ ಮಾಡಿ, ಅಪ್‌ಡೇಟ್‌ಗಳನ್ನು ಟ್ರ್ಯಾಕ್ ಮಾಡಿ',
      'leader': 'ನಾಯಕ',
      'leader_subtitle': 'ನಾಯಕರನ್ನು ಫಾಲೋ ಮಾಡಿ, ಡ್ಯಾಶ್‌ಬೋರ್ಡ್ ನೋಡಿ',
      'continue': 'ಮುಂದುವರಿಸಿ',
      'email': 'ಇಮೇಲ್',
      'password': 'ಪಾಸ್‌ವರ್ಡ್',
      'required': 'ಅಗತ್ಯ',
      'login_failed': 'ಲಾಗಿನ್ ವಿಫಲವಾಯಿತು',
      'role_redirect_note':
          'ಸೈನ್-ಇನ್ ನಂತರ ಪಾತ್ರದ ಆಧಾರದಲ್ಲಿ ರೀಡೈರೆಕ್ಟ್ ಆಗುತ್ತದೆ.',
      'language_changed': 'ಭಾಷೆ ಬದಲಾಯಿಸಲಾಗಿದೆ',
    },
    'Marathi': <String, String>{
      'connect_report_resolve': 'जोडा. तक्रार नोंदवा. समाधान मिळवा.',
      'heading_line_1': 'आपला नेता.',
      'heading_line_2': 'आपला समाज.',
      'heading_line_3': 'आपले भविष्य.',
      'get_started': 'सुरू करा',
      'login': 'लॉगिन',
      'choose_role': 'तुमची भूमिका निवडा',
      'citizen': 'नागरिक',
      'citizen_subtitle': 'समस्या नोंदवा, अपडेट्स ट्रॅक करा',
      'leader': 'नेता',
      'leader_subtitle': 'नेत्यांना फॉलो करा, डॅशबोर्ड पहा',
      'continue': 'पुढे चला',
      'email': 'ईमेल',
      'password': 'पासवर्ड',
      'required': 'आवश्यक',
      'login_failed': 'लॉगिन अयशस्वी',
      'role_redirect_note': 'साइन-इन नंतर भूमिकेनुसार रीडायरेक्ट होईल.',
      'language_changed': 'भाषा बदलली',
    },
    'Gujarati': <String, String>{
      'connect_report_resolve': 'જોડાઓ. રિપોર્ટ કરો. ઉકેલ મેળવો.',
      'heading_line_1': 'અમારા નેતા.',
      'heading_line_2': 'અમારો સમાજ.',
      'heading_line_3': 'અમારું ભવિષ્ય.',
      'get_started': 'શરૂ કરો',
      'login': 'લોગિન',
      'choose_role': 'તમારી ભૂમિકા પસંદ કરો',
      'citizen': 'નાગરિક',
      'citizen_subtitle': 'સમસ્યા રિપોર્ટ કરો, અપડેટ્સ ટ્રેક કરો',
      'leader': 'નેતા',
      'leader_subtitle': 'નેતાઓને ફોલો કરો, ડેશબોર્ડ જુઓ',
      'continue': 'આગળ વધો',
      'email': 'ઇમેલ',
      'password': 'પાસવર્ડ',
      'required': 'આવશ્યક',
      'login_failed': 'લોગિન નિષ્ફળ',
      'role_redirect_note': 'સાઇન-ઇન પછી ભૂમિકા પ્રમાણે રીડાયરેક્ટ થશે.',
      'language_changed': 'ભાષા બદલાઈ ગઈ',
    },
    'Punjabi': <String, String>{
      'connect_report_resolve': 'ਜੁੜੋ। ਰਿਪੋਰਟ ਕਰੋ। ਹੱਲ ਲੱਭੋ।',
      'heading_line_1': 'ਸਾਡਾ ਨੇਤਾ।',
      'heading_line_2': 'ਸਾਡੀ ਕਮਿਊਨਿਟੀ।',
      'heading_line_3': 'ਸਾਡਾ ਭਵਿੱਖ।',
      'get_started': 'ਸ਼ੁਰੂ ਕਰੋ',
      'login': 'ਲਾਗਇਨ',
      'choose_role': 'ਆਪਣੀ ਭੂਮਿਕਾ ਚੁਣੋ',
      'citizen': 'ਨਾਗਰਿਕ',
      'citizen_subtitle': 'ਸਮੱਸਿਆ ਰਿਪੋਰਟ ਕਰੋ, ਅਪਡੇਟ ਟ੍ਰੈਕ ਕਰੋ',
      'leader': 'ਨੇਤਾ',
      'leader_subtitle': 'ਨੇਤਾਵਾਂ ਨੂੰ ਫਾਲੋ ਕਰੋ, ਡੈਸ਼ਬੋਰਡ ਵੇਖੋ',
      'continue': 'ਅੱਗੇ ਵਧੋ',
      'email': 'ਈਮੇਲ',
      'password': 'ਪਾਸਵਰਡ',
      'required': 'ਲਾਜ਼ਮੀ',
      'login_failed': 'ਲਾਗਇਨ ਅਸਫਲ',
      'role_redirect_note': 'ਸਾਈਨ-ਇਨ ਤੋਂ ਬਾਅਦ ਭੂਮਿਕਾ ਅਨੁਸਾਰ ਰੀਡਾਇਰੈਕਟ ਹੋਵੇਗਾ।',
      'language_changed': 'ਭਾਸ਼ਾ ਬਦਲ ਗਈ',
    },
    'Bengali': <String, String>{
      'connect_report_resolve': 'সংযুক্ত হন। রিপোর্ট করুন। সমাধান পান।',
      'heading_line_1': 'আমাদের নেতা।',
      'heading_line_2': 'আমাদের সমাজ।',
      'heading_line_3': 'আমাদের ভবিষ্যৎ।',
      'get_started': 'শুরু করুন',
      'login': 'লগইন',
      'choose_role': 'আপনার ভূমিকা বেছে নিন',
      'citizen': 'নাগরিক',
      'citizen_subtitle': 'সমস্যা রিপোর্ট করুন, আপডেট ট্র্যাক করুন',
      'leader': 'নেতা',
      'leader_subtitle': 'নেতাদের ফলো করুন, ড্যাশবোর্ড দেখুন',
      'continue': 'এগিয়ে যান',
      'email': 'ইমেল',
      'password': 'পাসওয়ার্ড',
      'required': 'প্রয়োজনীয়',
      'login_failed': 'লগইন ব্যর্থ',
      'role_redirect_note': 'সাইন-ইন করার পরে ভূমিকা অনুযায়ী রিডাইরেক্ট হবে।',
      'language_changed': 'ভাষা পরিবর্তন হয়েছে',
    },
  };

  static const Map<String, String> _languageLabels = <String, String>{
    'English': 'English',
    'Telugu': 'తెలుగు',
    'Hindi': 'हिन्दी',
    'Tamil': 'தமிழ்',
    'Malayalam': 'മലയാളം',
    'Kannada': 'ಕನ್ನಡ',
    'Marathi': 'मराठी',
    'Gujarati': 'ગુજરાતી',
    'Punjabi': 'ਪੰਜਾਬੀ',
    'Bengali': 'বাংলা',
  };

  static String text(String language, String key) {
    final Map<String, String>? selected = _localizedValues[language];
    if (selected != null && selected.containsKey(key)) {
      return selected[key]!;
    }

    final Map<String, String> fallback =
        _localizedValues[fallbackLanguage] ?? <String, String>{};
    return fallback[key] ?? key;
  }

  static String languageLabel(String language) {
    return _languageLabels[language] ?? language;
  }
}
