class AppLocalizations {
  static const Map<String, Map<String, String>> _strings = {
    'English': {
      'select_language': 'Select Language',
      'choose_language': 'Choose your preferred language',
      'continue': 'Continue',
      'get_started': 'Get Started',
      'login': 'Login',
      'home': 'Home',
      'issues': 'Issues',
      'community': 'Community',
      'events': 'Events',
      'profile': 'Profile',
      'local': 'Local',
      'state': 'State',
      'national': 'National',
      'choose_role': 'Choose Role',
      'choose_your_role': 'Choose Your Role',
      'our_leader': 'Our Leader.',
      'our_community': 'Our Community.',
      'our_future': 'Our Future.',
      'citizen': 'Citizen',
      'leader': 'Leader',
      'citizen_subtitle': 'Report Issues, Track Updates',
      'leader_subtitle': 'Follow Leaders, View Dashboard',
      'notifications': 'Notifications',
      'alert_community_report': 'Community report approved in your ward.',
      'alert_state_digest': 'State analytics digest is ready to review.',
      'alert_new_feedback': 'New feedback received from citizens.',
      'alert_policy_briefing': 'National policy briefing starts in 30 minutes.',
      'notifications_enabled': 'Notifications enabled',
      'coming_soon': 'This section is coming soon',
      'all': 'All',
      'upcoming': 'Upcoming',
      'all_events': 'All Events',
      'ongoing': 'Ongoing',
      'completed': 'Completed',
      'featured_meeting': 'Featured Meeting',
      'upcoming_meetings': 'Upcoming Meetings',
      'search_meetings': 'Search meetings, events, keywords...',
      'going': 'Going',
      'rsvp_now': 'RSVP Now',
      'interested': 'Interested',
      'mark_interested': 'Mark Interested',
      'live_updates': 'Live Updates',
      'work_started': 'Work Started',
      'in_progress': 'In Progress',
      'update': 'Update',
      'notify_me_update': 'Notify Me on Update',
      'create_new': 'Create New',
      'close': 'Close',
      'create_post': 'Create Community Post',
      'create_post_subtitle': 'Share updates with your community',
      'create_event': 'Create Event',
      'create_event_subtitle': 'Organize and invite to events',
      'report_issue': 'Report Issue',
      'report_issue_subtitle': 'Report civic issues to authorities',
      'official_update': 'Official Update (Leader)',
      'official_update_subtitle': 'Share official update as a leader',
      'public_announcement': 'Public Announcement (Leader)',
      'public_announcement_subtitle': 'Make an important announcement',
      'settings': 'Settings',
      'settings_account': 'ACCOUNT',
      'settings_preferences': 'PREFERENCES',
      'settings_support': 'SUPPORT',
      'settings_danger_zone': 'DANGER ZONE',
      'edit_profile': 'Edit Profile',
      'privacy': 'Privacy',
      'change_password': 'Change Password',
      'dark_mode': 'Dark Mode',
      'light_mode': 'Light Mode',
      'language': 'Language',
      'help_center': 'Help Center',
      'about_app': 'About App',
      'logout': 'Logout',
      'delete_account': 'Delete Account',
      'delete_account_warning':
          'This action is permanent and cannot be undone.',
      'cancel': 'Cancel',
      'delete': 'Delete',
      'confirm': 'Confirmed',
      'active_citizen': 'Active Citizen',
      'posts': 'Posts',
      'issues_reported': 'Issues Reported',
      'issues_resolved': 'Issues Resolved',
      'events_attended': 'Events Attended',
      'my_posts': 'My Posts',
      'my_comments': 'My Comments',
      'my_reported_issues': 'My Reported Issues',
      'saved_posts': 'Saved Posts',
      'boost_citizen': 'Boost - Citizen',
      'unlock_premium_features': 'Unlock premium features',
      'role_citizen_line_1': 'Report issues.',
      'role_citizen_line_2': 'Track progress.',
      'role_citizen_line_3': 'Your community.',
      'role_leader_line_1': 'Monitor issues.',
      'role_leader_line_2': 'Engage citizens.',
      'role_leader_line_3': 'Drive development.',
      'footer_connecting': 'Connecting ',
      'footer_citizens': 'Citizens',
      'footer_empowering': '. Empowering ',
      'footer_leaders': 'Leaders',
      'footer_dot': '.',
      'role_ward_coordinator': 'Ward Coordinator',
      'role_municipal_lead': 'Municipal Lead',
      'role_community_officer': 'Community Officer',
      'role_block_supervisor': 'Block Supervisor',
      'role_state_coordinator': 'State Coordinator',
      'role_program_manager': 'Program Manager',
      'role_regional_director': 'Regional Director',
      'role_operations_lead': 'Operations Lead',
      'role_national_strategy_lead': 'National Strategy Lead',
      'role_operations_head': 'Operations Head',
      'role_policy_director': 'Policy Director',
      'role_transformation_lead': 'Transformation Lead',
      'local_msg_1':
          'Ward-level service dashboard is now live with transparent SLA tracking and weekly closure reports.',
      'local_msg_2':
          'Drainage and road maintenance tickets are now mapped by locality to improve response time this quarter.',
      'local_msg_3':
          'Citizen helpdesk now supports real-time issue routing to reduce duplicate complaints and backlog.',
      'local_msg_4':
          'Night safety lighting program has entered phase two with predictive outage monitoring enabled.',
      'local_msg_5':
          'We completed 100 percent geotag verification for sanitation requests across all neighborhood clusters.',
      'state_msg_1':
          'State scholarship onboarding crossed major milestones with faster verification and reduced drop-offs.',
      'state_msg_2':
          'District scorecards now publish weekly governance KPIs for education, health, and response performance.',
      'state_msg_3':
          'State service registry has been normalized to improve cross-department reporting and governance audits.',
      'state_msg_4':
          'A new escalation matrix reduced critical issue turnaround time by over 30 percent in pilot districts.',
      'state_msg_5':
          'We have launched a unified state command view for service continuity and performance tracking.',
      'national_msg_1':
          'National policy sprint delivered standardized digital service patterns now rolling out across departments.',
      'national_msg_2':
          'Cross-region command workflows are active with real-time escalation and measurable incident SLAs.',
      'national_msg_3':
          'National transformation framework now includes quarterly readiness scoring for platform-first delivery.',
      'national_msg_4':
          'Public service modernization roadmap has entered execution stage with focused KPI accountability.',
      'national_msg_5':
          'Inter-state operating model is now synchronized for data governance, reporting cadence, and resilience.',
    },
    'Telugu': {
      'select_language': 'భాషను ఎంచుకోండి',
      'choose_language': 'మీ ఇష్టమైన భాషను ఎంచుకోండి',
      'continue': 'కొనసాగించండి',
      'get_started': 'ప్రారంభించండి',
      'login': 'లాగిన్',
      'home': 'హోమ్',
      'issues': 'సమస్యలు',
      'events': 'ఈవెంట్లు',
      'profile': 'ప్రొఫైల్',
      'local': 'స్థానిక',
      'state': 'రాష్ట్ర',
      'national': 'జాతీయ',
      'choose_role': 'పాత్రను ఎంచుకోండి',
      'choose_your_role': 'మీ పాత్రను ఎంచుకోండి',
      'our_leader': 'మా నాయకుడు.',
      'our_community': 'మా సంఘం.',
      'our_future': 'మా భవిష్యత్తు.',
      'citizen': 'నాగరికుడు',
      'leader': 'నేత',
      'citizen_subtitle': 'సమస్యలను నివేదించండి, నవీకరణలను పర్యవేక్షించండి',
      'leader_subtitle': 'నేతలను అనుసరించండి, డాష్బోర్డ్ని వీక్షించండి',
      'notifications': 'నోటిఫికేషన్లు',
      'alert_community_report': 'మీ వార్డులో కమ్యూనిటీ నివేదిక ఆమోదించబడింది.',
      'alert_state_digest': 'రాష్ట్ర విశ్లేషణ సారాంశం సమీక్షకు సిద్ధంగా ఉంది.',
      'alert_new_feedback': 'పౌరుల నుండి కొత్త అభిప్రాయం వచ్చింది.',
      'alert_policy_briefing':
          'జాతీయ విధాన వివరణ 30 నిమిషాల్లో ప్రారంభమవుతుంది.',
      'notifications_enabled': 'నోటిఫికేషన్లు ప్రారంభించబడ్డాయి',
      'coming_soon': 'ఈ విభాగం త్వరలో అందుబాటులోకి వస్తుంది',
      'all': 'అన్నీ',
      'upcoming': 'రాబోయేవి',
      'all_events': 'అన్ని ఈవెంట్లు',
      'ongoing': 'జరుగుతోంది',
      'completed': 'పూర్తయింది',
      'featured_meeting': 'ప్రత్యేక సమావేశం',
      'upcoming_meetings': 'రాబోయే సమావేశాలు',
      'search_meetings': 'సమావేశాలు, ఈవెంట్లు, కీలకపదాలు వెతకండి...',
      'going': 'హాజరవుతున్నాను',
      'rsvp_now': 'ఇప్పుడే RSVP చేయండి',
      'interested': 'ఆసక్తి ఉంది',
      'mark_interested': 'ఆసక్తిగా గుర్తించు',
      'live_updates': 'లైవ్ అప్డేట్లు',
      'work_started': 'పని ప్రారంభమైంది',
      'in_progress': 'ప్రగతిలో ఉంది',
      'update': 'అప్డేట్',
      'notify_me_update': 'అప్డేట్ వచ్చినప్పుడు తెలియజేయండి',
      'create_new': 'కొత్తది సృష్టించండి',
      'close': 'మూసివేయండి',
      'create_post': 'కమ్యూనిటీ పోస్ట్ సృష్టించండి',
      'create_post_subtitle': 'మీ కమ్యూనిటితో అప్డేట్లను పంచుకోండి',
      'create_event': 'ఈవెంట్ సృష్టించండి',
      'create_event_subtitle': 'ఈవెంట్లను నిర్వహించి ఆహ్వానించండి',
      'report_issue': 'సమస్యను నివేదించండి',
      'report_issue_subtitle': 'పౌర సమస్యలను అధికారులకు తెలియజేయండి',
      'official_update': 'అధికారిక అప్డేట్ (లీడర్)',
      'official_update_subtitle': 'లీడర్‌గా అధికారిక అప్డేట్ పంచుకోండి',
      'public_announcement': 'ప్రజా ప్రకటన (లీడర్)',
      'public_announcement_subtitle': 'ముఖ్యమైన ప్రకటన చేయండి',
      'settings': 'సెట్టింగ్స్',
      'settings_account': 'ఖాతా',
      'settings_preferences': 'అభిరుచులు',
      'settings_support': 'సహాయం',
      'settings_danger_zone': 'డేంజర్ జోన్',
      'edit_profile': 'ప్రొఫైల్ సవరించండి',
      'privacy': 'గోప్యత',
      'change_password': 'పాస్‌వర్డ్ మార్చండి',
      'dark_mode': 'డార్క్ మోడ్',
      'light_mode': 'లైట్ మోడ్',
      'language': 'భాష',
      'help_center': 'సహాయ కేంద్రం',
      'about_app': 'యాప్ గురించి',
      'logout': 'లాగ్ఔట్',
      'delete_account': 'ఖాతా తొలగించండి',
      'delete_account_warning': 'ఈ చర్య శాశ్వతం మరియు తిరిగి మార్చలేరు.',
      'cancel': 'రద్దు',
      'delete': 'తొలగించు',
      'confirm': 'నిర్ధారించబడింది',
      'active_citizen': 'సక్రియ పౌరుడు',
      'posts': 'పోస్టులు',
      'issues_reported': 'నివేదించిన సమస్యలు',
      'issues_resolved': 'పరిష్కరించిన సమస్యలు',
      'events_attended': 'హాజరైన ఈవెంట్లు',
      'my_posts': 'నా పోస్టులు',
      'my_comments': 'నా కామెంట్లు',
      'my_reported_issues': 'నేను నివేదించిన సమస్యలు',
      'saved_posts': 'సేవ్ చేసిన పోస్టులు',
      'role_citizen_line_1': 'సమస్యలను నివేదించండి.',
      'role_citizen_line_2': 'పురోగతిని ట్రాక్ చేయండి.',
      'role_citizen_line_3': 'మీ సమాజం.',
      'role_leader_line_1': 'సమస్యలను పర్యవేక్షించండి.',
      'role_leader_line_2': 'పౌరులతో మమేకం అవ్వండి.',
      'role_leader_line_3': 'అభివృద్ధిని నడిపించండి.',
      'footer_connecting': 'కలుపుతున్నాం ',
      'footer_citizens': 'పౌరులను',
      'footer_empowering': '. శక్తినిస్తున్నాం ',
      'footer_leaders': 'నాయకులకు',
      'footer_dot': '.',
      'role_ward_coordinator': 'వార్డ్ కోఆర్డినేటర్',
      'role_municipal_lead': 'మున్సిపల్ లీడ్',
      'role_community_officer': 'కమ్యూనిటీ ఆఫీసర్',
      'role_block_supervisor': 'బ్లాక్ సూపర్వైజర్',
      'role_state_coordinator': 'రాష్ట్ర కోఆర్డినేటర్',
      'role_program_manager': 'ప్రోగ్రాం మేనేజర్',
      'role_regional_director': 'ప్రాంతీయ డైరెక్టర్',
      'role_operations_lead': 'ఆపరేషన్స్ లీడ్',
      'role_national_strategy_lead': 'జాతీయ వ్యూహ లీడ్',
      'role_operations_head': 'ఆపరేషన్స్ హెడ్',
      'role_policy_director': 'పాలసీ డైరెక్టర్',
      'role_transformation_lead': 'ట్రాన్స్‌ఫార్మేషన్ లీడ్',
      'local_msg_1':
          'వార్డ్ స్థాయి సేవల డ్యాష్‌బోర్డ్ ఇప్పుడు పారదర్శక SLA ట్రాకింగ్ మరియు వారంవారీ ముగింపు నివేదికలతో అందుబాటులో ఉంది.',
      'local_msg_2':
          'ఈ త్రైమాసికంలో స్పందన సమయాన్ని మెరుగుపరచడానికి డ్రైనేజ్ మరియు రోడ్డు నిర్వహణ టికెట్లు ప్రాంతాలవారీగా మ్యాప్ చేయబడ్డాయి.',
      'local_msg_3':
          'డూప్లికేట్ ఫిర్యాదులు మరియు పెండింగ్‌ను తగ్గించేందుకు సిటిజన్ హెల్ప్‌డెస్క్ ఇప్పుడు రియల్-టైమ్ ఇష్యూ రూటింగ్‌ను మద్దతిస్తోంది.',
      'local_msg_4':
          'రాత్రి భద్రతా లైటింగ్ కార్యక్రమం ప్రెడిక్టివ్ అవుటేజ్ మానిటరింగ్‌తో రెండో దశలోకి ప్రవేశించింది.',
      'local_msg_5':
          'అన్ని కాలనీలలో శానిటేషన్ అభ్యర్థనలకు 100 శాతం జియోట్యాగ్ ధృవీకరణను పూర్తి చేశాం.',
      'state_msg_1':
          'రాష్ట్ర స్కాలర్‌షిప్ ఆన్‌బోర్డింగ్ వేగవంతమైన ధృవీకరణతో మరియు తగ్గించిన డ్రాప్-ఆఫ్‌లతో ప్రధాన మైలురాళ్లను దాటింది.',
      'state_msg_2':
          'విద్య, ఆరోగ్యం మరియు సేవా స్పందన పనితీరు కోసం జిల్లా స్కోర్‌కార్డులు ఇప్పుడు వారంవారీ గవర్నెన్స్ KPIలను ప్రచురిస్తున్నాయి.',
      'state_msg_3':
          'అంతర్విభాగ నివేదికలు మరియు గవర్నెన్స్ ఆడిట్‌లను మెరుగుపరచడానికి రాష్ట్ర సేవా రిజిస్ట్రీ సాధారణీకరించబడింది.',
      'state_msg_4':
          'కొత్త ఎస్కలేషన్ మ్యాట్రిక్స్ పైలట్ జిల్లాల్లో కీలక సమస్యల పరిష్కార సమయాన్ని 30 శాతానికి పైగా తగ్గించింది.',
      'state_msg_5':
          'సేవా నిరంతరత మరియు పనితీరు ట్రాకింగ్ కోసం ఏకీకృత రాష్ట్ర కమాండ్ వ్యూ ప్రారంభించాము.',
      'national_msg_1':
          'జాతీయ పాలసీ స్ప్రింట్ ప్రామాణిక డిజిటల్ సేవా నమూనాలను అందించింది; అవి ఇప్పుడు విభాగాలవ్యాప్తంగా అమలవుతున్నాయి.',
      'national_msg_2':
          'క్రాస్-రీజన్ కమాండ్ వర్క్‌ఫ్లోలు రియల్-టైమ్ ఎస్కలేషన్ మరియు కొలిచగల ఇన్సిడెంట్ SLAలతో కార్యాచరణలో ఉన్నాయి.',
      'national_msg_3':
          'జాతీయ ట్రాన్స్‌ఫార్మేషన్ ఫ్రేమ్‌వర్క్‌లో ప్లాట్‌ఫామ్-ఫస్ట్ డెలివరీ కోసం త్రైమాసిక సిద్ధత స్కోరింగ్ ఇప్పుడు చేర్చబడింది.',
      'national_msg_4':
          'పబ్లిక్ సర్వీస్ మోడర్నైజేషన్ రోడ్‌మ్యాప్ స్పష్టమైన KPI బాధ్యతతో అమలు దశలోకి ప్రవేశించింది.',
      'national_msg_5':
          'డేటా గవర్నెన్స్, రిపోర్టింగ్ కేడెన్స్ మరియు రెసిలియెన్స్ కోసం అంతర్రాష్ట్ర ఆపరేటింగ్ మోడల్ సమకాలీకరించబడింది.',
    },
    'Hindi': {
      'select_language': 'भाषा चुनें',
      'choose_language': 'अपनी पसंदीदा भाषा चुनें',
      'continue': 'जारी रखें',
      'get_started': 'शुरू करें',
      'login': 'लॉगिन',
      'home': 'होम',
      'issues': 'मुद्दे',
      'events': 'ईवेंट्स',
      'profile': 'प्रोफ़ाइल',
      'local': 'स्थानीय',
      'state': 'राज्य',
      'national': 'राष्ट्रीय',
      'choose_role': 'भूमिका चुनें',
      'choose_your_role': 'अपनी भूमिका चुनें',
      'our_leader': 'हमारा नेता।',
      'our_community': 'हमारा समुदाय।',
      'our_future': 'हमारा भविष्य।',
      'citizen': 'नागरिक',
      'leader': 'नेता',
      'citizen_subtitle': 'समस्याएँ रिपोर्ट करें, अपडेट ट्रैक करें',
      'leader_subtitle': 'नेताओं का पालन करें, डैशबोर्ड देखें',
      'notifications': 'सूचनाएं',
      'alert_community_report': 'आपके वार्ड में सामुदायिक रिपोर्ट स्वीकृत हुई।',
      'alert_state_digest': 'राज्य एनालिटिक्स सारांश समीक्षा के लिए तैयार है।',
      'alert_new_feedback': 'नागरिकों से नया फीडबैक मिला है।',
      'alert_policy_briefing': 'राष्ट्रीय नीति ब्रीफिंग 30 मिनट में शुरू होगी।',
      'notifications_enabled': 'सूचनाएं सक्षम हैं',
      'coming_soon': 'यह सेक्शन जल्द उपलब्ध होगा',
      'all': 'सभी',
      'upcoming': 'आगामी',
      'all_events': 'सभी इवेंट्स',
      'ongoing': 'जारी',
      'completed': 'पूर्ण',
      'featured_meeting': 'विशेष बैठक',
      'upcoming_meetings': 'आगामी बैठकें',
      'search_meetings': 'बैठकें, इवेंट्स, कीवर्ड खोजें...',
      'going': 'जा रहा/रही हूं',
      'rsvp_now': 'अभी RSVP करें',
      'interested': 'रुचि है',
      'mark_interested': 'रुचि दर्ज करें',
      'live_updates': 'लाइव अपडेट्स',
      'work_started': 'काम शुरू हुआ',
      'in_progress': 'प्रगति पर',
      'update': 'अपडेट',
      'notify_me_update': 'अपडेट आने पर सूचित करें',
      'create_new': 'नया बनाएं',
      'close': 'बंद करें',
      'create_post': 'कम्युनिटी पोस्ट बनाएं',
      'create_post_subtitle': 'अपने समुदाय के साथ अपडेट साझा करें',
      'create_event': 'इवेंट बनाएं',
      'create_event_subtitle': 'इवेंट आयोजित करें और आमंत्रित करें',
      'report_issue': 'समस्या रिपोर्ट करें',
      'report_issue_subtitle': 'नागरिक समस्याएं अधिकारियों तक पहुंचाएं',
      'official_update': 'आधिकारिक अपडेट (नेता)',
      'official_update_subtitle': 'नेता के रूप में आधिकारिक अपडेट साझा करें',
      'public_announcement': 'सार्वजनिक घोषणा (नेता)',
      'public_announcement_subtitle': 'एक महत्वपूर्ण घोषणा करें',
      'settings': 'सेटिंग्स',
      'settings_account': 'खाता',
      'settings_preferences': 'प्राथमिकताएँ',
      'settings_support': 'सहायता',
      'settings_danger_zone': 'डेंजर ज़ोन',
      'edit_profile': 'प्रोफ़ाइल संपादित करें',
      'privacy': 'गोपनीयता',
      'change_password': 'पासवर्ड बदलें',
      'dark_mode': 'डार्क मोड',
      'light_mode': 'लाइट मोड',
      'language': 'भाषा',
      'help_center': 'सहायता केंद्र',
      'about_app': 'ऐप के बारे में',
      'logout': 'लॉगआउट',
      'delete_account': 'खाता हटाएं',
      'delete_account_warning':
          'यह कार्रवाई स्थायी है और वापस नहीं की जा सकती।',
      'cancel': 'रद्द करें',
      'delete': 'हटाएं',
      'confirm': 'पुष्टि हुई',
      'active_citizen': 'सक्रिय नागरिक',
      'posts': 'पोस्ट्स',
      'issues_reported': 'रिपोर्ट की गई समस्याएं',
      'issues_resolved': 'सुलझी समस्याएं',
      'events_attended': 'अटेंड किए गए इवेंट्स',
      'my_posts': 'मेरी पोस्ट्स',
      'my_comments': 'मेरी टिप्पणियां',
      'my_reported_issues': 'मेरी रिपोर्ट की गई समस्याएं',
      'saved_posts': 'सहेजी गई पोस्ट्स',
      'role_citizen_line_1': 'समस्याएं रिपोर्ट करें।',
      'role_citizen_line_2': 'प्रगति ट्रैक करें।',
      'role_citizen_line_3': 'आपका समुदाय।',
      'role_leader_line_1': 'समस्याओं की निगरानी करें।',
      'role_leader_line_2': 'नागरिकों से जुड़ें।',
      'role_leader_line_3': 'विकास को आगे बढ़ाएं।',
      'footer_connecting': 'जोड़ते हुए ',
      'footer_citizens': 'नागरिकों को',
      'footer_empowering': '. सशक्त बनाते हुए ',
      'footer_leaders': 'नेताओं को',
      'footer_dot': '.',
      'role_ward_coordinator': 'वार्ड कोऑर्डिनेटर',
      'role_municipal_lead': 'म्यूनिसिपल लीड',
      'role_community_officer': 'कम्युनिटी ऑफिसर',
      'role_block_supervisor': 'ब्लॉक सुपरवाइज़र',
      'role_state_coordinator': 'राज्य कोऑर्डिनेटर',
      'role_program_manager': 'प्रोग्राम मैनेजर',
      'role_regional_director': 'क्षेत्रीय निदेशक',
      'role_operations_lead': 'ऑपरेशन्स लीड',
      'role_national_strategy_lead': 'राष्ट्रीय रणनीति लीड',
      'role_operations_head': 'ऑपरेशन्स हेड',
      'role_policy_director': 'पॉलिसी डायरेक्टर',
      'role_transformation_lead': 'ट्रांसफॉर्मेशन लीड',
      'local_msg_1':
          'वार्ड-स्तरीय सेवा डैशबोर्ड अब पारदर्शी SLA ट्रैकिंग और साप्ताहिक क्लोजर रिपोर्ट के साथ लाइव है।',
      'local_msg_2':
          'इस तिमाही प्रतिक्रिया समय सुधारने के लिए ड्रेनेज और रोड मेंटेनेंस टिकट अब स्थानीयता के अनुसार मैप किए गए हैं।',
      'local_msg_3':
          'डुप्लिकेट शिकायतें और बैकलॉग कम करने के लिए सिटीजन हेल्पडेस्क अब रियल-टाइम इश्यू रूटिंग सपोर्ट करता है।',
      'local_msg_4':
          'रात्रि सुरक्षा लाइटिंग कार्यक्रम चरण-दो में प्रवेश कर चुका है और इसमें प्रेडिक्टिव आउटेज मॉनिटरिंग सक्षम है।',
      'local_msg_5':
          'हमने सभी पड़ोस क्लस्टरों में स्वच्छता अनुरोधों के लिए 100 प्रतिशत जियोटैग सत्यापन पूरा किया है।',
      'state_msg_1':
          'तेज सत्यापन और कम ड्रॉप-ऑफ के साथ राज्य स्कॉलरशिप ऑनबोर्डिंग ने महत्वपूर्ण माइलस्टोन पार किए हैं।',
      'state_msg_2':
          'जिला स्कोरकार्ड अब शिक्षा, स्वास्थ्य और प्रतिक्रिया प्रदर्शन के लिए साप्ताहिक गवर्नेंस KPI प्रकाशित करते हैं।',
      'state_msg_3':
          'क्रॉस-डिपार्टमेंट रिपोर्टिंग और गवर्नेंस ऑडिट सुधारने हेतु राज्य सेवा रजिस्ट्री को मानकीकृत किया गया है।',
      'state_msg_4':
          'नई एस्केलेशन मैट्रिक्स ने पायलट जिलों में गंभीर मुद्दों के समाधान समय को 30 प्रतिशत से अधिक घटाया है।',
      'state_msg_5':
          'सेवा निरंतरता और प्रदर्शन ट्रैकिंग के लिए हमने एकीकृत राज्य कमांड व्यू लॉन्च किया है।',
      'national_msg_1':
          'राष्ट्रीय नीति स्प्रिंट ने मानकीकृत डिजिटल सेवा पैटर्न दिए हैं जो अब विभागों में रोलआउट हो रहे हैं।',
      'national_msg_2':
          'क्रॉस-रीजन कमांड वर्कफ़्लो अब रियल-टाइम एस्केलेशन और मापनीय इंसीडेंट SLA के साथ सक्रिय हैं।',
      'national_msg_3':
          'राष्ट्रीय ट्रांसफॉर्मेशन फ्रेमवर्क में अब प्लेटफ़ॉर्म-फर्स्ट डिलीवरी हेतु तिमाही रेडीनेस स्कोरिंग शामिल है।',
      'national_msg_4':
          'पब्लिक सर्विस मॉडर्नाइज़ेशन रोडमैप स्पष्ट KPI जवाबदेही के साथ कार्यान्वयन चरण में प्रवेश कर चुका है।',
      'national_msg_5':
          'डेटा गवर्नेंस, रिपोर्टिंग कैडेंस और रेज़िलिएंस के लिए अंतर-राज्य संचालन मॉडल अब सिंक्रोनाइज़ हो चुका है।',
    },
    'Tamil': {
      'select_language': 'மொழியைத் தேர்ந்தெடுக்கவும்',
      'choose_language': 'உங்கள் விருப்ப மொழியைத் தேர்ந்தெடுக்கவும்',
      'continue': 'தொடரவும்',
      'get_started': 'தொடங்கவும்',
      'login': 'உள்நுழை',
      'home': 'முகப்பு',
      'issues': 'சிக்கல்கள்',
      'events': 'நிகழ்வுகள்',
      'profile': 'சுயவிவரம்',
      'local': 'உள்ளூர்',
      'state': 'மாநில',
      'national': 'தேசிய',
      'choose_role': 'பதவியைத் தேர்ந்தெடுக்கவும்',
      'choose_your_role': 'உங்கள் பாத்திரத்தை தேர்ந்தெடுக்கவும்',
      'our_leader': 'எங்கள் தலைவர்.',
      'our_community': 'எங்கள் சமூகம்.',
      'our_future': 'எங்கள் எதிர்காலம்.',
      'citizen': 'குடிமகன்',
      'leader': 'தலைவர்',
      'citizen_subtitle':
          'சிக்கல்களைப் புகாரளிக்கவும், புதுப்பிப்புகளைப் பின்பற்றவும்',
      'leader_subtitle': 'தலைவர்களைப் பின்பற்றவும், டாஷ்போர்டைப் பார்க்கவும்',
      'role_citizen_line_1': 'சிக்கல்களை பதிவு செய்யுங்கள்.',
      'role_citizen_line_2': 'முன்னேற்றத்தை கண்காணிக்கவும்.',
      'role_citizen_line_3': 'உங்கள் சமூகத்திற்காக.',
      'role_leader_line_1': 'சிக்கல்களை கண்காணிக்கவும்.',
      'role_leader_line_2': 'மக்களுடன் இணைந்திருங்கள்.',
      'role_leader_line_3': 'வளர்ச்சியை முன்னெடுக்கவும்.',
      'footer_connecting': 'இணைக்கும் ',
      'footer_citizens': 'குடிமக்களை',
      'footer_empowering': '. வலுப்படுத்தும் ',
      'footer_leaders': 'தலைவர்களை',
      'footer_dot': '.',
      'role_ward_coordinator': 'வார்டு ஒருங்கிணைப்பாளர்',
      'role_municipal_lead': 'முனிசிபல் லீட்',
      'role_community_officer': 'சமூக அதிகாரி',
      'role_block_supervisor': 'பிளாக் மேற்பார்வையாளர்',
      'role_state_coordinator': 'மாநில ஒருங்கிணைப்பாளர்',
      'role_program_manager': 'திட்ட மேலாளர்',
      'role_regional_director': 'பிராந்திய இயக்குநர்',
      'role_operations_lead': 'செயல்பாட்டு முன்னிலை',
      'role_national_strategy_lead': 'தேசிய மூலோபாய முன்னிலை',
      'role_operations_head': 'செயல்பாட்டு தலைவர்',
      'role_policy_director': 'கொள்கை இயக்குநர்',
      'role_transformation_lead': 'மாற்ற முன்னிலை',
      'local_msg_1':
          'வார்டு சேவை டாஷ்போர்டு இப்போது வெளிப்படையான SLA கண்காணிப்பு மற்றும் வாராந்திர நிறைவு அறிக்கைகளுடன் இயங்குகிறது.',
      'local_msg_2':
          'இந்த காலாண்டில் பதில் நேரத்தை மேம்படுத்த வடிகால் மற்றும் சாலை பராமரிப்பு டிக்கெட்டுகள் பகுதிவாரியாக வரைபடம் செய்யப்பட்டுள்ளது.',
      'local_msg_3':
          'மீண்டும் வரும் புகார்களை குறைக்க குடிமக்கள் உதவி மையம் இப்போது நேரடி பிரச்சனை வழிமாற்றை ஆதரிக்கிறது.',
      'local_msg_4':
          'இரவு பாதுகாப்பு விளக்கு திட்டம் இரண்டாம் கட்டத்திற்கு சென்றுள்ளது; முன்னறிவிப்பு கண்காணிப்பு இயலுமைப்படுத்தப்பட்டுள்ளது.',
      'local_msg_5':
          'அனைத்து பகுதிகளிலும் சுகாதார கோரிக்கைகளுக்கு 100 சதவீத ஜியோடேக் சரிபார்ப்பு முடிக்கப்பட்டது.',
      'state_msg_1':
          'மாநில கல்வி உதவி சேர்க்கை வேகமான சரிபார்ப்பு மூலம் முக்கிய மைல்கற்களை கடந்துள்ளது.',
      'state_msg_2':
          'கல்வி, சுகாதாரம் மற்றும் பதில் செயல்திறனுக்கான மாவட்ட KPIகள் இப்போது வாராந்திரமாக வெளியிடப்படுகின்றன.',
      'state_msg_3':
          'துறைமாறான அறிக்கைகளை மேம்படுத்த மாநில சேவை பதிவேடு ஒரே மாதிரியாக்கப்பட்டது.',
      'state_msg_4':
          'புதிய எஸ்கலேஷன் அமைப்பு முன்மாதிரி மாவட்டங்களில் முக்கிய பிரச்சனை தீர்வு நேரத்தை 30 சதவீதத்திற்கும் மேல் குறைத்தது.',
      'state_msg_5':
          'சேவை தொடர்ச்சி மற்றும் செயல்திறன் கண்காணிப்புக்கான ஒருங்கிணைந்த மாநில கட்டுப்பாட்டு காட்சி தொடங்கப்பட்டது.',
      'national_msg_1':
          'தேசிய கொள்கை ஸ்பிரிண்ட் மூலம் தரநிலையான டிஜிட்டல் சேவை முறைமைகள் துறைகளில் நடைமுறைப்படுத்தப்படுகின்றன.',
      'national_msg_2':
          'பிராந்தியங்களுக்கிடையிலான கட்டுப்பாட்டு பணிச்சூழல்கள் நேரடி எஸ்கலேஷன் SLAகளுடன் செயல்படுகின்றன.',
      'national_msg_3':
          'தேசிய மாற்ற வடிவமைப்பில் காலாண்டு தயார்நிலை மதிப்பீடு சேர்க்கப்பட்டுள்ளது.',
      'national_msg_4':
          'பொது சேவை நவீனமயமாக்கல் சாலை வரைபடம் KPI பொறுப்புடன் செயல்படுத்தும் கட்டத்தில் உள்ளது.',
      'national_msg_5':
          'தரவு ஆட்சி மற்றும் அறிக்கை ஒழுங்குக்காக மாநிலங்களுக்கு இடையேயான செயல்பாட்டு மாதிரி ஒத்திசைக்கப்பட்டது.',
    },
    'Malayalam': {
      'select_language': 'ഭാഷ തിരഞ്ഞെടുക്കുക',
      'choose_language': 'നിങ്ങളുടെ ഇഷ്ടമുള്ള ഭാഷ തിരഞ്ഞെടുക്കുക',
      'continue': 'തുടരുക',
      'get_started': 'ആരംഭിക്കുക',
      'login': 'ലോഗിൻ',
      'home': 'ഹോം',
      'issues': 'സമയസൂചകങ്ങൾ',
      'events': 'ഇവന്റുകൾ',
      'profile': 'പ്രൊഫൈൽ',
      'local': 'പ്രാദേശികം',
      'state': 'സംസ്ഥാനം',
      'national': 'ദേശീയം',
      'choose_role': 'भूमിക തിരഞ്ഞെടുക്കുക',
      'choose_your_role': 'നിങ്ങളുടെ role തിരഞ്ഞെടുക്കുക',
      'our_leader': 'നമ്മുടെ നേതാവ്.',
      'our_community': 'നമ്മുടെ സമുദായം.',
      'our_future': 'നമ്മുടെ ഭാവി.',
      'citizen': 'നാഗരികൻ',
      'leader': 'നേതാവ്',
      'citizen_subtitle':
          'പ്രശ്നങ്ങൾ റിപ്പോർട്ട് ചെയ്യുക, അപ്ഡേറ്റുകൾ ട്രാക്ക് ചെയ്യുക',
      'leader_subtitle': 'നേതാക്കളെ പിന്തുടരുക, ഡാഷ്ബോർഡ് കാണുക',
      'role_citizen_line_1': 'പ്രശ്നങ്ങൾ റിപ്പോർട്ട് ചെയ്യൂ.',
      'role_citizen_line_2': 'പുരോഗതി പിന്തുടരൂ.',
      'role_citizen_line_3': 'നിങ്ങളുടെ സമൂഹത്തിനായി.',
      'role_leader_line_1': 'പ്രശ്നങ്ങൾ നിരീക്ഷിക്കൂ.',
      'role_leader_line_2': 'പൗരന്മാരുമായി ഇടപെടൂ.',
      'role_leader_line_3': 'വികസനം മുന്നോട്ട് കൊണ്ടുപോവൂ.',
      'footer_connecting': 'ബന്ധിപ്പിക്കുന്നത് ',
      'footer_citizens': 'പൗരന്മാരെ',
      'footer_empowering': '. ശക്തമാക്കുന്നത് ',
      'footer_leaders': 'നേതാക്കളെ',
      'footer_dot': '.',
      'role_ward_coordinator': 'വാർഡ് കോഓർഡിനേറ്റർ',
      'role_municipal_lead': 'മുനിസിപ്പൽ ലീഡ്',
      'role_community_officer': 'കമ്മ്യൂണിറ്റി ഓഫീസർ',
      'role_block_supervisor': 'ബ്ലോക്ക് സൂപ്പർവൈസർ',
      'role_state_coordinator': 'സംസ്ഥാന കോഓർഡിനേറ്റർ',
      'role_program_manager': 'പ്രോഗ്രാം മാനേജർ',
      'role_regional_director': 'പ്രാദേശിക ഡയറക്ടർ',
      'role_operations_lead': 'ഓപ്പറേഷൻസ് ലീഡ്',
      'role_national_strategy_lead': 'ദേശീയ തന്ത്ര ലീഡ്',
      'role_operations_head': 'ഓപ്പറേഷൻസ് ഹെഡ്',
      'role_policy_director': 'പോളിസി ഡയറക്ടർ',
      'role_transformation_lead': 'ട്രാൻസ്ഫർമേഷൻ ലീഡ്',
      'local_msg_1':
          'വാർഡ് തല സേവന ഡാഷ്ബോർഡ് ഇപ്പോൾ SLA ട്രാക്കിംഗും ആഴ്ച്ചതോറുള്ള ക്ലോഷർ റിപ്പോർട്ടുകളും സഹിതം ലൈവിലാണ്.',
      'local_msg_2':
          'ഈ പാദത്തിൽ പ്രതികരണ സമയം മെച്ചപ്പെടുത്താൻ ഡ്രെയിനേജ്, റോഡ് മെയിന്റനൻസ് ടിക്കറ്റുകൾ പ്രദേശംവാരി മാപ്പ് ചെയ്തിട്ടുണ്ട്.',
      'local_msg_3':
          'ഡ്യൂപ്ലിക്കേറ്റ് പരാതികൾ കുറയ്ക്കാൻ സിറ്റിസൺ ഹെൽപ്‌ഡെസ്ക് റിയൽ-ടൈം ഇഷ്യൂ റൂട്ടിംഗ് പിന്തുണക്കുന്നു.',
      'local_msg_4':
          'നൈറ്റ് സേഫ്റ്റി ലൈറ്റിംഗ് പരിപാടി രണ്ടാം ഘട്ടത്തിലേക്ക് കടന്നു; പ്രവചനാത്മക നിരീക്ഷണം സജ്ജമാക്കി.',
      'local_msg_5':
          'എല്ലാ പ്രദേശങ്ങളിലുമുള്ള ശുചിത്വ അഭ്യർത്ഥനകൾക്ക് 100 ശതമാനം ജിയോടാഗ് പരിശോധന പൂർത്തിയാക്കി.',
      'state_msg_1':
          'സംസ്ഥാന സ്കോളർഷിപ്പ് ഓൺബോർഡിംഗ് വേഗത്തിലുള്ള പരിശോധനയോടെ പ്രധാന മൈൽസ്റ്റോണുകൾ പിന്നിട്ടു.',
      'state_msg_2':
          'വിദ്യാഭ്യാസം, ആരോഗ്യം, പ്രതികരണ പ്രകടനം എന്നിവയ്ക്കുള്ള ജില്ല KPIകൾ ആഴ്ച്ചതോറും പ്രസിദ്ധീകരിക്കുന്നു.',
      'state_msg_3':
          'വകുപ്പുതല റിപ്പോർട്ടിംഗ് മെച്ചപ്പെടുത്താൻ സംസ്ഥാന സർവീസ് രജിസ്ട്രി സ്റ്റാൻഡേർഡൈസ് ചെയ്തു.',
      'state_msg_4':
          'പുതിയ എസ്കലേഷൻ ഘടന പൈലറ്റ് ജില്ലകളിൽ നിർണായക പ്രശ്ന പരിഹാര സമയം 30 ശതമാനത്തിൽ കൂടുതലായി കുറച്ചു.',
      'state_msg_5':
          'സേവന തുടർച്ചയ്ക്കും പ്രകടന നിരീക്ഷണത്തിനുമായി ഏകീകൃത സംസ്ഥാന കമാൻഡ് വ്യൂ ആരംഭിച്ചു.',
      'national_msg_1':
          'ദേശീയ നയ സ്പ്രിന്റ് സ്റ്റാൻഡേർഡ് ഡിജിറ്റൽ സേവന മാതൃകകൾ നൽകി; അവ ഇപ്പോൾ വകുപ്പുകളിലാകെ നടപ്പിലാക്കുന്നു.',
      'national_msg_2':
          'ക്രോസ്-റീജൻ കമാൻഡ് വർക്ക്‌ഫ്ലോകൾ റിയൽ-ടൈം എസ്കലേഷനും SLAയും സഹിതം സജ്ജമാണ്.',
      'national_msg_3':
          'ദേശീയ ട്രാൻസ്ഫർമേഷൻ ഫ്രെയിംവർകിൽ ത്രൈമാസ തയ്യാറെടുപ്പ് സ്കോറിംഗ് ഉൾപ്പെടുത്തി.',
      'national_msg_4':
          'പബ്ലിക് സർവീസ് മോഡേണൈസേഷൻ റോഡ്മാപ്പ് KPI ഉത്തരവാദിത്തത്തോടെ നടപ്പിലാക്കൽ ഘട്ടത്തിലേക്ക് കടന്നു.',
      'national_msg_5':
          'ഡാറ്റ ഗവേണൻസ്, റിപ്പോർട്ടിംഗ് രീതികൾ, റെസിലിയൻസ് എന്നിവയ്ക്കായി അന്തർസംസ്ഥാന മോഡൽ ഒത്തുചേർന്നു.',
    },
    'Kannada': {
      'select_language': 'ಭಾಷೆಯನ್ನು ಆಯ್ಕೆ ಮಾಡಿ',
      'choose_language': 'ನಿಮ್ಮ ಪ್ರೀತಿಯ ಭಾಷೆಯನ್ನು ಆಯ್ಕೆ ಮಾಡಿ',
      'continue': 'ಮುಂದುವರಿಸಿ',
      'get_started': 'ಆರಂಭಿಸಿ',
      'login': 'ಲಾಗಿನ್',
      'home': 'ಹೋಂ',
      'issues': 'ಸಮಸ್ಯಗಳು',
      'events': 'ಇವೆಂಟ್ಸ್',
      'profile': 'ಪ್ರೊಫೈಲ್',
      'local': 'ಸ್ಥಳೀಯ',
      'state': 'ರಾಜ್ಯ',
      'national': 'ಜాతీయ',
      'choose_role': 'ಪಾತ್ರವನ್ನು ಆಯ್ಕೆ ಮಾಡಿ',
      'choose_your_role': 'ನಿಮ್ಮ ಪಾತ್ರವನ್ನು ಆಯ್ಕೆ ಮಾಡಿ',
      'our_leader': 'ನಮ್ಮ ನಾಯಕ.',
      'our_community': 'ನಮ್ಮ ಸಮುದಾಯ.',
      'our_future': 'ನಮ್ಮ ಭವಿಷ್ಯ.',
      'citizen': 'ನಾಗರಿಕ',
      'leader': 'ನಾಯಕ್',
      'citizen_subtitle': 'ಸಮಸ್ಯಗಳನ್ನು ವರದಿ ಮಾಡಿ, ನವೀಕರಣಗಳನ್ನು ಟ್ರ್ಯಾಕ್ ಮಾಡಿ',
      'leader_subtitle': 'ನೇತृत्वವನ್ನು ಅನುಸರಿಸಿ, ಡ್ಯಾಶ್ಬೋರ್ಡ್ കാണಿ',
      'role_citizen_line_1': 'ಸಮಸ್ಯೆಗಳನ್ನು ವರದಿ ಮಾಡಿ.',
      'role_citizen_line_2': 'ಪ್ರಗತಿಯನ್ನು ಟ್ರ್ಯಾಕ್ ಮಾಡಿ.',
      'role_citizen_line_3': 'ನಿಮ್ಮ ಸಮುದಾಯಕ್ಕಾಗಿ.',
      'role_leader_line_1': 'ಸಮಸ್ಯೆಗಳನ್ನು ನಿಗಾ ಮಾಡಿ.',
      'role_leader_line_2': 'ನಾಗರಿಕರೊಂದಿಗೆ ಸಂಪರ್ಕದಲ್ಲಿರಿ.',
      'role_leader_line_3': 'ಅಭಿವೃದ್ಧಿಯನ್ನು ಮುನ್ನಡೆಸಿ.',
      'footer_connecting': 'ಕೊಂಡೊಯ್ಯುವುದು ',
      'footer_citizens': 'ನಾಗರಿಕರನ್ನು',
      'footer_empowering': '. ಶಕ್ತಿಗೊಳಿಸುವುದು ',
      'footer_leaders': 'ನಾಯಕರನ್ನು',
      'footer_dot': '.',
      'role_ward_coordinator': 'ವಾರ್ಡ್ ಸಂಯೋಜಕ',
      'role_municipal_lead': 'ಮುನಿಸಿಪಲ್ ಲೀಡ್',
      'role_community_officer': 'ಕಮ್ಯುನಿಟಿ ಅಧಿಕಾರಿ',
      'role_block_supervisor': 'ಬ್ಲಾಕ್ ಸೂಪರ್ವೈಸರ್',
      'role_state_coordinator': 'ರಾಜ್ಯ ಸಂಯೋಜಕ',
      'role_program_manager': 'ಕಾರ್ಯಕ್ರಮ ವ್ಯವಸ್ಥಾಪಕ',
      'role_regional_director': 'ಪ್ರಾದೇಶಿಕ ನಿರ್ದೇಶಕ',
      'role_operations_lead': 'ಆಪರೇಷನ್ಸ್ ಲೀಡ್',
      'role_national_strategy_lead': 'ರಾಷ್ಟ್ರೀಯ ತಂತ್ರ ಲೀಡ್',
      'role_operations_head': 'ಆಪರೇಷನ್ಸ್ ಮುಖ್ಯಸ್ಥ',
      'role_policy_director': 'ನೀತಿ ನಿರ್ದೇಶಕ',
      'role_transformation_lead': 'ರೂಪಾಂತರ ಲೀಡ್',
      'local_msg_1':
          'ವಾರ್ಡ್ ಮಟ್ಟದ ಸೇವಾ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್ ಈಗ SLA ಟ್ರ್ಯಾಕಿಂಗ್ ಮತ್ತು ವಾರಂತ್ಯ ಕ್ಲೋಸರ್ ವರದಿಗಳೊಂದಿಗೆ ಲೈವ್ ಆಗಿದೆ.',
      'local_msg_2':
          'ಈ ತ್ರೈಮಾಸಿಕದಲ್ಲಿ ಪ್ರತಿಕ್ರಿಯೆ ಸಮಯ ಸುಧಾರಿಸಲು ಡ್ರೈನೇಜ್ ಮತ್ತು ರಸ್ತೆ ನಿರ್ವಹಣಾ ಟಿಕೆಟ್‌ಗಳನ್ನು ಪ್ರದೇಶವಾರು ಮ್ಯಾಪ್ ಮಾಡಲಾಗಿದೆ.',
      'local_msg_3':
          'ಡ್ಯುಪ್ಲಿಕೇಟ್ ದೂರುಗಳನ್ನು ಕಡಿಮೆ ಮಾಡಲು ಸಿಟಿಜನ್ ಹೆಲ್ಪ್‌ಡೆಸ್ಕ್ ಈಗ ರಿಯಲ್-ಟೈಮ್ ಇಶ್ಯೂ ರೂಟಿಂಗ್ ಅನ್ನು ಬೆಂಬಲಿಸುತ್ತದೆ.',
      'local_msg_4':
          'ರಾತ್ರಿ ಭದ್ರತಾ ಬೆಳಕು ಕಾರ್ಯಕ್ರಮ ಎರಡನೇ ಹಂತಕ್ಕೆ ಪ್ರವೇಶಿಸಿದೆ; ಪ್ರಿಡಿಕ್ಟಿವ್ ಮಾನಿಟರಿಂಗ್ ಸಕ್ರಿಯಗೊಂಡಿದೆ.',
      'local_msg_5':
          'ಎಲ್ಲಾ ಪ್ರದೇಶಗಳಲ್ಲಿ ಸ್ವಚ್ಛತಾ ವಿನಂತಿಗಳಿಗೆ 100 ಪ್ರತಿಶತ ಜಿಯೋಟ್ಯಾಗ್ ಪರಿಶೀಲನೆಯನ್ನು ಪೂರ್ಣಗೊಳಿಸಿದ್ದೇವೆ.',
      'state_msg_1':
          'ರಾಜ್ಯ ವಿದ್ಯಾರ್ಥಿವೇತನ ಆನ್‌ಬೋರ್ಡಿಂಗ್ ವೇಗವಾದ ಪರಿಶೀಲನೆ ಮೂಲಕ ಪ್ರಮುಖ ಮೈಲಿಗಲ್ಲುಗಳನ್ನು ದಾಟಿದೆ.',
      'state_msg_2':
          'ಶಿಕ್ಷಣ, ಆರೋಗ್ಯ ಮತ್ತು ಪ್ರತಿಕ್ರಿಯೆ ಕಾರ್ಯಕ್ಷಮತೆಗಾಗಿ ಜಿಲ್ಲಾ KPIಗಳನ್ನು ಈಗ ವಾರಂವಾರ ಪ್ರಕಟಿಸಲಾಗುತ್ತಿದೆ.',
      'state_msg_3':
          'ವಿಭಾಗಾಂತರ ವರದಿ ಮತ್ತು ಆಡಳಿತ ಪರಿಶೀಲನೆ ಸುಧಾರಿಸಲು ರಾಜ್ಯ ಸೇವಾ ನೋಂದಣಿಯನ್ನು ಮಾನಕಗೊಳಿಸಲಾಗಿದೆ.',
      'state_msg_4':
          'ಹೊಸ ಎಸ್ಕಲೇಶನ್ ವ್ಯವಸ್ಥೆ ಪೈಲಟ್ ಜಿಲ್ಲೆಗಳಲ್ಲಿ ಗಂಭೀರ ಸಮಸ್ಯೆ ಪರಿಹಾರ ಸಮಯವನ್ನು 30 ಪ್ರತಿಶತಕ್ಕಿಂತ ಹೆಚ್ಚು ಕಡಿಮೆ ಮಾಡಿದೆ.',
      'state_msg_5':
          'ಸೇವೆ ನಿರಂತರತೆ ಮತ್ತು ಕಾರ್ಯಕ್ಷಮತೆ ಟ್ರ್ಯಾಕಿಂಗ್‌ಗೆ ಏಕೀಕೃತ ರಾಜ್ಯ ಕಮಾಂಡ್ ವ್ಯೂ ಆರಂಭಿಸಲಾಗಿದೆ.',
      'national_msg_1':
          'ರಾಷ್ಟ್ರೀಯ ನೀತಿ ಸ್ಪ್ರಿಂಟ್ ಮಾನಕ ಡಿಜಿಟಲ್ ಸೇವಾ ಮಾದರಿಗಳನ್ನು ನೀಡಿದ್ದು, ಅವು ಈಗ ಇಲಾಖೆಗಳಾದ್ಯಂತ ಜಾರಿಗೆ ಬರುತ್ತಿವೆ.',
      'national_msg_2':
          'ಕ್ರಾಸ್-ರೀಜನ್ ಕಮಾಂಡ್ ವರ್ಕ್‌ಫ್ಲೋಗಳು ರಿಯಲ್-ಟೈಮ್ ಎಸ್ಕಲೇಶನ್ ಮತ್ತು SLAಗಳೊಂದಿಗೆ ಸಕ್ರಿಯವಾಗಿವೆ.',
      'national_msg_3':
          'ರಾಷ್ಟ್ರೀಯ ರೂಪಾಂತರ ಫ್ರೇಮ್‌ವರ್ಕ್‌ನಲ್ಲಿ ತ್ರೈಮಾಸಿಕ ಸಿದ್ಧತಾ ಅಂಕೆಗಳು ಸೇರಿಸಲಾಗಿದೆ.',
      'national_msg_4':
          'ಸಾರ್ವಜನಿಕ ಸೇವಾ ಆಧುನೀಕರಣ ರಸ್ತೆನಕ್ಷೆ KPI ಹೊಣೆಗಾರಿಕೆಯಿಂದ ಜಾರಿಗೆ ಸಾಗುತ್ತಿದೆ.',
      'national_msg_5':
          'ಡೇಟಾ ಆಡಳಿತ, ವರದಿ ಕ್ರಮ ಮತ್ತು ಸ್ಥೈರ್ಯಕ್ಕಾಗಿ ಅಂತರ್-ರಾಜ್ಯ ಕಾರ್ಯಾಚರಣೆ ಮಾದರಿ ಈಗ ಸಮನ್ವಯಗೊಂಡಿದೆ.',
    },
    'Marathi': {
      'select_language': 'भाषा निवडा',
      'choose_language': 'आपली आवडती भाषा निवडा',
      'continue': 'पुढे जा',
      'get_started': 'सुरू करा',
      'login': 'लॉगिन',
      'home': 'होम',
      'issues': 'समस्या',
      'events': 'कार्यक्रम',
      'profile': 'प्रोफाइल',
      'local': 'स्थानिक',
      'state': 'राज्य',
      'national': 'राष्ट्रीय',
      'choose_role': 'भूमिका निवडा',
      'choose_your_role': 'तुमची भूमिका निवडा',
      'our_leader': 'आमचा नेता.',
      'our_community': 'आमचे समुदाय.',
      'our_future': 'आमचे भविष्य.',
      'citizen': 'नागरिक',
      'leader': 'नेता',
      'citizen_subtitle': 'समस्या नोंदवा, अपडेट ट्रॅक करा',
      'leader_subtitle': 'नेत्यांचे अनुसरण करा, डॅशबोर्ड पाहा',
      'role_citizen_line_1': 'समस्या नोंदवा.',
      'role_citizen_line_2': 'प्रगती ट्रॅक करा.',
      'role_citizen_line_3': 'तुमच्या समुदायासाठी.',
      'role_leader_line_1': 'समस्यांवर लक्ष ठेवा.',
      'role_leader_line_2': 'नागरिकांशी जोडलेले रहा.',
      'role_leader_line_3': 'विकासाला गती द्या.',
      'footer_connecting': 'जोडत आहोत ',
      'footer_citizens': 'नागरिकांना',
      'footer_empowering': '. सक्षम करत आहोत ',
      'footer_leaders': 'नेत्यांना',
      'footer_dot': '.',
      'role_ward_coordinator': 'वॉर्ड समन्वयक',
      'role_municipal_lead': 'म्युनिसिपल लीड',
      'role_community_officer': 'कम्युनिटी ऑफिसर',
      'role_block_supervisor': 'ब्लॉक सुपरवायझर',
      'role_state_coordinator': 'राज्य समन्वयक',
      'role_program_manager': 'कार्यक्रम व्यवस्थापक',
      'role_regional_director': 'प्रादेशिक संचालक',
      'role_operations_lead': 'ऑपरेशन्स लीड',
      'role_national_strategy_lead': 'राष्ट्रीय धोरण लीड',
      'role_operations_head': 'ऑपरेशन्स प्रमुख',
      'role_policy_director': 'धोरण संचालक',
      'role_transformation_lead': 'ट्रान्सफॉर्मेशन लीड',
      'local_msg_1':
          'वॉर्ड-स्तरीय सेवा डॅशबोर्ड आता पारदर्शक SLA ट्रॅकिंग आणि साप्ताहिक क्लोजर अहवालांसह लाईव्ह आहे.',
      'local_msg_2':
          'या तिमाहीत प्रतिसाद वेळ सुधारण्यासाठी ड्रेनेज आणि रस्ता देखभाल तिकिटे क्षेत्रानुसार नकाशित केली आहेत.',
      'local_msg_3':
          'डुप्लिकेट तक्रारी कमी करण्यासाठी नागरिक हेल्पडेस्क आता रिअल-टाइम इश्यू रूटिंगला समर्थन देतो.',
      'local_msg_4':
          'रात्रीच्या सुरक्षा प्रकाशयोजना कार्यक्रमाने दुसऱ्या टप्प्यात प्रवेश केला आहे; भविष्यसूचक मॉनिटरिंग सक्षम केले आहे.',
      'local_msg_5':
          'सर्व परिसर क्लस्टर्समध्ये स्वच्छता विनंत्यांसाठी 100 टक्के जिओटॅग पडताळणी पूर्ण केली आहे.',
      'state_msg_1':
          'राज्य शिष्यवृत्ती ऑनबोर्डिंगने जलद पडताळणीसह महत्त्वाचे टप्पे पार केले आहेत.',
      'state_msg_2':
          'शिक्षण, आरोग्य आणि प्रतिसाद कामगिरीसाठी जिल्हा KPI आता साप्ताहिक प्रकाशित होतात.',
      'state_msg_3':
          'विभागीय अहवाल आणि प्रशासन ऑडिट सुधारण्यासाठी राज्य सेवा नोंदणी मानकीकृत केली आहे.',
      'state_msg_4':
          'नवीन एस्कलेशन फ्रेमवर्कने पायलट जिल्ह्यांमध्ये गंभीर समस्या निराकरण वेळ 30 टक्क्यांहून अधिक कमी केला.',
      'state_msg_5':
          'सेवा सातत्य आणि कामगिरी ट्रॅकिंगसाठी एकत्रित राज्य कमांड व्ह्यू सुरू केला आहे.',
      'national_msg_1':
          'राष्ट्रीय धोरण स्प्रिंटमुळे प्रमाणित डिजिटल सेवा नमुने मिळाले असून ते आता विभागांमध्ये लागू होत आहेत.',
      'national_msg_2':
          'क्रॉस-रीजन कमांड वर्कफ्लो आता रिअल-टाइम एस्कलेशन आणि मोजता येणाऱ्या SLAसह सक्रिय आहेत.',
      'national_msg_3':
          'राष्ट्रीय ट्रान्सफॉर्मेशन फ्रेमवर्कमध्ये तिमाही तयारी स्कोअरिंग समाविष्ट केले आहे.',
      'national_msg_4':
          'सार्वजनिक सेवा आधुनिकीकरण रोडमॅप KPI जवाबदारीसह अंमलबजावणी टप्प्यात दाखल झाला आहे.',
      'national_msg_5':
          'डेटा गव्हर्नन्स, अहवाल लय आणि लवचिकतेसाठी आंतर-राज्य कार्यप्रणाली आता समक्रमित झाली आहे.',
    },
    'Gujarati': {
      'select_language': 'ભાષા પસંદ કરો',
      'choose_language': 'તમારી પસંદની ભાષા પસંદ કરો',
      'continue': 'ચાલુ રાખો',
      'get_started': 'શરૂ કરો',
      'login': 'લૉગિન',
      'home': 'હોમ',
      'issues': 'સમસ્યાઓ',
      'events': 'ઇવેન્ટ્સ',
      'profile': 'પ્રોફાઇલ',
      'local': 'સ્થાનિક',
      'state': 'રાજ્ય',
      'national': 'રાષ્ટ્રીય',
      'choose_role': 'ભૂમિકા પસંદ કરો',
      'choose_your_role': 'તમારી ભૂમિકા પસંદ કરો',
      'our_leader': 'અમારો नेता.',
      'our_community': 'અમારો સમુદાય.',
      'our_future': 'અમારો ભવિષ્ય.',
      'citizen': 'નાગરિક',
      'leader': 'नेતા',
      'citizen_subtitle': 'સમસ્યાઓની જાણ કરો, અપડેટ્સને ટ્રૅક કરો',
      'leader_subtitle': 'नेતૃઓનું પાલન કરો, ડેશબોર્ડ જુઓ',
      'role_citizen_line_1': 'સમસ્યાઓ રિપોર્ટ કરો.',
      'role_citizen_line_2': 'પ્રગતિ ટ્રેક કરો.',
      'role_citizen_line_3': 'તમારા સમુદાય માટે.',
      'role_leader_line_1': 'સમસ્યાઓ પર નજર રાખો.',
      'role_leader_line_2': 'નાગરિકો સાથે જોડાયેલા રહો.',
      'role_leader_line_3': 'વિકાસ આગળ વધારો.',
      'footer_connecting': 'જોડતા ',
      'footer_citizens': 'નાગરિકોને',
      'footer_empowering': '. સશક્ત બનાવતા ',
      'footer_leaders': 'નેતાઓને',
      'footer_dot': '.',
      'role_ward_coordinator': 'વોર્ડ સંયોજક',
      'role_municipal_lead': 'મ્યુનિસિપલ લીડ',
      'role_community_officer': 'સમુદાય અધિકારી',
      'role_block_supervisor': 'બ્લોક સુપરવાઇઝર',
      'role_state_coordinator': 'રાજ્ય સંયોજક',
      'role_program_manager': 'કાર્યક્રમ મેનેજર',
      'role_regional_director': 'પ્રાદેશિક નિર્દેશક',
      'role_operations_lead': 'ઓપરેશન્સ લીડ',
      'role_national_strategy_lead': 'રાષ્ટ્રીય વ્યૂહરચના લીડ',
      'role_operations_head': 'ઓપરેશન્સ હેડ',
      'role_policy_director': 'નીતિ નિર્દેશક',
      'role_transformation_lead': 'ટ્રાન્સફોર્મેશન લીડ',
      'local_msg_1':
          'વોર્ડ સ્તરની સેવા ડેશબોર્ડ હવે પારદર્શક SLA ટ્રેકિંગ અને સાપ્તાહિક ક્લોઝર રિપોર્ટ સાથે લાઈવ છે.',
      'local_msg_2':
          'આ ત્રિમાસિકમાં પ્રતિસાદ સમય સુધારવા ડ્રેનેજ અને રોડ મેન્ટેનન્સ ટિકિટો વિસ્તારવાર મેપ કરવામાં આવી છે.',
      'local_msg_3':
          'ડુપ્લિકેટ ફરિયાદો ઘટાડવા સિટિઝન હેલ્પડેસ્ક હવે રિયલ-ટાઇમ ઈશ્યુ રૂટિંગ સપોર્ટ કરે છે.',
      'local_msg_4':
          'રાત્રી સુરક્ષા લાઇટિંગ કાર્યક્રમ બીજા તબક્કામાં પ્રવેશ્યો છે; પ્રેડિક્ટિવ મોનિટરિંગ સક્રિય છે.',
      'local_msg_5':
          'બધા વિસ્તારોમાં સ્વચ્છતા વિનંતિઓ માટે 100 ટકા જીઓટેગ વેરીફિકેશન પૂર્ણ થયું છે.',
      'state_msg_1':
          'રાજ્ય સ્કોલરશિપ ઓનબોર્ડિંગ ઝડપી ચકાસણી સાથે મહત્વપૂર્ણ માઈલસ્ટોન પાર કરી ગયું છે.',
      'state_msg_2':
          'શિક્ષણ, આરોગ્ય અને પ્રતિસાદ પ્રદર્શન માટે જિલ્લા KPI હવે સાપ્તાહિક પ્રકાશિત થાય છે.',
      'state_msg_3':
          'વિભાગીય રિપોર્ટિંગ અને ગવર્નન્સ ઓડિટ સુધારવા રાજ્ય સર્વિસ રજિસ્ટ્રી સ્ટાન્ડર્ડાઈઝ કરવામાં આવી છે.',
      'state_msg_4':
          'નવી એસ્કલેશન મેટ્રિક્સે પાઇલટ જિલ્લાઓમાં ગંભીર મુદ્દા ઉકેલ સમય 30 ટકા કરતાં વધુ ઘટાડ્યો.',
      'state_msg_5':
          'સેવા સતતતા અને પ્રદર્શન ટ્રેકિંગ માટે એકીકૃત રાજ્ય કમાન્ડ વ્યૂ લોન્ચ કરવામાં આવ્યું છે.',
      'national_msg_1':
          'રાષ્ટ્રીય નીતિ સ્પ્રિન્ટે સ્ટાન્ડર્ડ ડિજિટલ સેવા પેટર્ન આપ્યા છે જે હવે વિભાગોમાં લાગુ થઈ રહ્યા છે.',
      'national_msg_2':
          'ક્રોસ-રીજન કમાન્ડ વર્કફ્લો હવે રિયલ-ટાઇમ એસ્કલેશન અને માપનીય SLA સાથે સક્રિય છે.',
      'national_msg_3':
          'રાષ્ટ્રીય ટ્રાન્સફોર્મેશન ફ્રેમવર્કમાં ત્રિમાસિક તૈયારીઓનું સ્કોરિંગ ઉમેરાયું છે.',
      'national_msg_4':
          'પબ્લિક સર્વિસ મોડર્નાઇઝેશન રોડમૅપ KPI જવાબદારી સાથે અમલીકરણ તબક્કામાં પ્રવેશ્યો છે.',
      'national_msg_5':
          'ડેટા ગવર્નન્સ, રિપોર્ટિંગ કેડન્સ અને રિઝિલિયન્સ માટે આંતરરાજ્ય ઓપરેટિંગ મોડલ હવે સમન્વિત છે.',
    },
    'Punjabi': {
      'select_language': 'ਭਾਸ਼ਾ ਚੁਣੋ',
      'choose_language': 'ਆਪਣੀ ਪਸੰਦੀਦਾ ਭਾਸ਼ਾ ਚੁਣੋ',
      'continue': 'ਜਾਰੀ ਰੱਖੋ',
      'get_started': 'ਸ਼ੁਰੂ ਕਰੋ',
      'login': 'ਲੌਗਿਨ',
      'home': 'ਹੋਮ',
      'issues': 'ਮੁੱਦੇ',
      'events': 'ਈਵੈਂਟਸ',
      'profile': 'ਪ੍ਰੋਫਾਈਲ',
      'local': 'ਸਥਾਨਕ',
      'state': 'ਰਾਜ',
      'national': 'ਰਾਸ਼ਟਰੀ',
      'choose_role': 'ਰੋਲ ਚੁਣੋ',
      'choose_your_role': 'ਆਪਣਾ ਰੋਲ ਚੁਣੋ',
      'our_leader': 'ਸਾਡਾ ਨੇਤਾ.',
      'our_community': 'ਸਾਡਾ ਭਾਈਚਾਰਾ.',
      'our_future': 'ਸਾਡਾ ਭਵਿੱਖ.',
      'citizen': 'ਨਾਗਰੀਕ',
      'leader': 'ਨੇਤਾ',
      'citizen_subtitle': 'ਮੁੱਦੇ ਰਿਪੋਰਟ ਕਰੋ, ਅੱਪਡੇਟ ਟਰੈਕ ਕਰੋ',
      'leader_subtitle': 'नेताओं ਨੂੰ ਫ਼ਾਲੋ ਕਰੋ, ਡੈਸ਼ਬੋਰਡ ਦੇਖੋ',
      'role_citizen_line_1': 'ਮੁੱਦੇ ਰਿਪੋਰਟ ਕਰੋ।',
      'role_citizen_line_2': 'ਤਰੱਕੀ ਟਰੈਕ ਕਰੋ।',
      'role_citizen_line_3': 'ਤੁਹਾਡੇ ਸਮੂਹ ਲਈ।',
      'role_leader_line_1': 'ਮੁੱਦਿਆਂ ਦੀ ਨਿਗਰਾਨੀ ਕਰੋ।',
      'role_leader_line_2': 'ਨਾਗਰਿਕਾਂ ਨਾਲ ਜੁੜੇ ਰਹੋ।',
      'role_leader_line_3': 'ਵਿਕਾਸ ਨੂੰ ਅੱਗੇ ਵਧਾਓ।',
      'footer_connecting': 'ਜੋੜਦੇ ਹੋਏ ',
      'footer_citizens': 'ਨਾਗਰਿਕਾਂ ਨੂੰ',
      'footer_empowering': '. ਸਮਰੱਥ ਬਣਾਉਂਦੇ ਹੋਏ ',
      'footer_leaders': 'ਨੇਤਾਵਾਂ ਨੂੰ',
      'footer_dot': '.',
      'role_ward_coordinator': 'ਵਾਰਡ ਕੋਆਰਡੀਨੇਟਰ',
      'role_municipal_lead': 'ਮਿਊਨਿਸਿਪਲ ਲੀਡ',
      'role_community_officer': 'ਕਮਿਊਨਿਟੀ ਅਫਸਰ',
      'role_block_supervisor': 'ਬਲੌਕ ਸੁਪਰਵਾਈਜ਼ਰ',
      'role_state_coordinator': 'ਸਟੇਟ ਕੋਆਰਡੀਨੇਟਰ',
      'role_program_manager': 'ਪ੍ਰੋਗਰਾਮ ਮੈਨੇਜਰ',
      'role_regional_director': 'ਖੇਤਰੀ ਡਾਇਰੈਕਟਰ',
      'role_operations_lead': 'ਓਪਰੇਸ਼ਨਜ਼ ਲੀਡ',
      'role_national_strategy_lead': 'ਰਾਸ਼ਟਰੀ ਰਣਨੀਤੀ ਲੀਡ',
      'role_operations_head': 'ਓਪਰੇਸ਼ਨਜ਼ ਹੈਡ',
      'role_policy_director': 'ਪਾਲਿਸੀ ਡਾਇਰੈਕਟਰ',
      'role_transformation_lead': 'ਟਰਾਂਸਫਾਰਮੇਸ਼ਨ ਲੀਡ',
      'local_msg_1':
          'ਵਾਰਡ ਪੱਧਰੀ ਸੇਵਾ ਡੈਸ਼ਬੋਰਡ ਹੁਣ SLA ਟਰੈਕਿੰਗ ਅਤੇ ਹਫ਼ਤਾਵਾਰੀ ਕਲੋਜ਼ਰ ਰਿਪੋਰਟਾਂ ਨਾਲ ਲਾਈਵ ਹੈ।',
      'local_msg_2':
          'ਇਸ ਤਿਮਾਹੀ ਵਿੱਚ ਜਵਾਬੀ ਸਮਾਂ ਸੁਧਾਰਨ ਲਈ ਡਰੇਨੇਜ ਅਤੇ ਰੋਡ ਮੇਨਟੇਨੈਂਸ ਟਿਕਟਾਂ ਨੂੰ ਇਲਾਕਾ-ਵਾਰ ਮੈਪ ਕੀਤਾ ਗਿਆ ਹੈ।',
      'local_msg_3':
          'ਡੁਪਲੀਕੇਟ ਸ਼ਿਕਾਇਤਾਂ ਘਟਾਉਣ ਲਈ ਸਿਟਿਜ਼ਨ ਹੈਲਪਡੈਸਕ ਹੁਣ ਰੀਅਲ-ਟਾਈਮ ਇਸ਼ਿਊ ਰੂਟਿੰਗ ਦਾ ਸਮਰਥਨ ਕਰਦਾ ਹੈ।',
      'local_msg_4':
          'ਨਾਈਟ ਸੇਫਟੀ ਲਾਈਟਿੰਗ ਪ੍ਰੋਗਰਾਮ ਦੂਜੇ ਪੜਾਅ ਵਿੱਚ ਦਾਖਲ ਹੋ ਗਿਆ ਹੈ; ਪ੍ਰੀਡਿਕਟਿਵ ਮੋਨੀਟਰਿੰਗ ਸਮਰਥਿਤ ਹੈ।',
      'local_msg_5':
          'ਸਾਰੇ ਇਲਾਕਿਆਂ ਵਿੱਚ ਸੈਨਿਟੇਸ਼ਨ ਬੇਨਤੀਆਂ ਲਈ 100 ਫੀਸਦੀ ਜਿਓਟੈਗ ਤਸਦੀਕ ਪੂਰੀ ਹੋ ਗਈ ਹੈ।',
      'state_msg_1':
          'ਸਟੇਟ ਸਕਾਲਰਸ਼ਿਪ ਆਨਬੋਰਡਿੰਗ ਤੇਜ਼ ਤਸਦੀਕ ਨਾਲ ਮਹੱਤਵਪੂਰਨ ਮਾਈਲਸਟੋਨ ਪਾਰ ਕਰ ਚੁੱਕੀ ਹੈ।',
      'state_msg_2':
          'ਸਿੱਖਿਆ, ਸਿਹਤ ਅਤੇ ਜਵਾਬੀ ਪ੍ਰਦਰਸ਼ਨ ਲਈ ਜ਼ਿਲ੍ਹਾ KPI ਹੁਣ ਹਫ਼ਤਾਵਾਰੀ ਪ੍ਰਕਾਸ਼ਿਤ ਹੁੰਦੇ ਹਨ।',
      'state_msg_3':
          'ਵਿਭਾਗੀ ਰਿਪੋਰਟਿੰਗ ਸੁਧਾਰਨ ਲਈ ਸਟੇਟ ਸਰਵਿਸ ਰਜਿਸਟਰੀ ਨੂੰ ਮਿਆਰੀਕ੍ਰਿਤ ਕੀਤਾ ਗਿਆ ਹੈ।',
      'state_msg_4':
          'ਨਵੇਂ ਐਸਕਲੇਸ਼ਨ ਫਰੇਮਵਰਕ ਨੇ ਪਾਇਲਟ ਜ਼ਿਲ੍ਹਿਆਂ ਵਿੱਚ ਗੰਭੀਰ ਮੁੱਦੇ ਹੱਲ ਸਮਾਂ 30 ਫੀਸਦੀ ਤੋਂ ਵੱਧ ਘਟਾਇਆ ਹੈ।',
      'state_msg_5':
          'ਸੇਵਾ ਲਗਾਤਾਰਤਾ ਅਤੇ ਪ੍ਰਦਰਸ਼ਨ ਟਰੈਕਿੰਗ ਲਈ ਇਕਜੁਟ ਸਟੇਟ ਕਮਾਂਡ ਵਿਊ ਲਾਂਚ ਕੀਤਾ ਗਿਆ ਹੈ।',
      'national_msg_1':
          'ਰਾਸ਼ਟਰੀ ਨੀਤੀ ਸਪ੍ਰਿੰਟ ਨੇ ਮਿਆਰੀ ਡਿਜ਼ੀਟਲ ਸੇਵਾ ਪੈਟਰਨ ਦਿੱਤੇ ਹਨ ਜੋ ਹੁਣ ਵਿਭਾਗਾਂ ਵਿੱਚ ਲਾਗੂ ਹੋ ਰਹੇ ਹਨ।',
      'national_msg_2':
          'ਕਰਾਸ-ਰੀਜਨ ਕਮਾਂਡ ਵਰਕਫਲੋ ਹੁਣ ਰੀਅਲ-ਟਾਈਮ ਐਸਕਲੇਸ਼ਨ ਅਤੇ SLA ਨਾਲ ਸਰਗਰਮ ਹਨ।',
      'national_msg_3':
          'ਰਾਸ਼ਟਰੀ ਟਰਾਂਸਫਾਰਮੇਸ਼ਨ ਫਰੇਮਵਰਕ ਵਿੱਚ ਤਿਮਾਹੀ ਤਿਆਰੀ ਸਕੋਰਿੰਗ ਸ਼ਾਮਲ ਕੀਤੀ ਗਈ ਹੈ।',
      'national_msg_4':
          'ਪਬਲਿਕ ਸਰਵਿਸ ਮਾਡਰਨਾਈਜ਼ੇਸ਼ਨ ਰੋਡਮੈਪ KPI ਜ਼ਿੰਮੇਵਾਰੀ ਨਾਲ ਲਾਗੂ ਕਰਨ ਦੇ ਪੜਾਅ ਵਿੱਚ ਦਾਖਲ ਹੋ ਗਿਆ ਹੈ।',
      'national_msg_5':
          'ਡਾਟਾ ਗਵਰਨੈਂਸ, ਰਿਪੋਰਟਿੰਗ ਅਤੇ ਲਚੀਲੇਪਣ ਲਈ ਅੰਤਰ-ਰਾਜ ਮਾਡਲ ਹੁਣ ਸਮਕਾਲੀਕ੍ਰਿਤ ਹੈ।',
    },
    'Bengali': {
      'select_language': 'ভাষা বেছে নিন',
      'choose_language': 'আপনার পছন্দের ভাষা বেছে নিন',
      'continue': 'চালিয়ে যান',
      'get_started': 'শুরু করুন',
      'login': 'লগইন',
      'home': 'হোম',
      'issues': 'সমস্যা',
      'events': 'ইভেন্টস',
      'profile': 'প্রোফাইল',
      'local': 'স্থানীয়',
      'state': 'রাজ্য',
      'national': 'জাতীয়',
      'choose_role': 'ভূমিকা বেছে নিন',
      'choose_your_role': 'আপনার ভূমিকা বেছে নিন',
      'our_leader': 'আমাদের নেতা।',
      'our_community': 'আমাদের সম্প্রদায়।',
      'our_future': 'আমাদের ভবিষ্যৎ।',
      'citizen': 'নাগরিক',
      'leader': 'নেতা',
      'citizen_subtitle': 'সমস্যা রিপোর্ট করুন, আপডেট ট্র্যাক করুন',
      'leader_subtitle': 'নেতাদের অনুসরণ করুন, ড্যাশবোর্ড দেখুন',
      'role_citizen_line_1': 'সমস্যা রিপোর্ট করুন।',
      'role_citizen_line_2': 'অগ্রগতি ট্র্যাক করুন।',
      'role_citizen_line_3': 'আপনার সম্প্রদায়ের জন্য।',
      'role_leader_line_1': 'সমস্যা পর্যবেক্ষণ করুন।',
      'role_leader_line_2': 'নাগরিকদের সঙ্গে যুক্ত থাকুন।',
      'role_leader_line_3': 'উন্নয়ন এগিয়ে নিন।',
      'footer_connecting': 'সংযুক্ত করছি ',
      'footer_citizens': 'নাগরিকদের',
      'footer_empowering': '. সক্ষম করছি ',
      'footer_leaders': 'নেতাদের',
      'footer_dot': '.',
      'role_ward_coordinator': 'ওয়ার্ড কোঅর্ডিনেটর',
      'role_municipal_lead': 'মিউনিসিপাল লিড',
      'role_community_officer': 'কমিউনিটি অফিসার',
      'role_block_supervisor': 'ব্লক সুপারভাইজার',
      'role_state_coordinator': 'রাজ্য কোঅর্ডিনেটর',
      'role_program_manager': 'প্রোগ্রাম ম্যানেজার',
      'role_regional_director': 'আঞ্চলিক পরিচালক',
      'role_operations_lead': 'অপারেশনস লিড',
      'role_national_strategy_lead': 'জাতীয় কৌশল লিড',
      'role_operations_head': 'অপারেশনস প্রধান',
      'role_policy_director': 'পলিসি ডিরেক্টর',
      'role_transformation_lead': 'ট্রান্সফরমেশন লিড',
      'local_msg_1':
          'ওয়ার্ড-স্তরের সার্ভিস ড্যাশবোর্ড এখন স্বচ্ছ SLA ট্র্যাকিং এবং সাপ্তাহিক ক্লোজার রিপোর্টসহ লাইভ।',
      'local_msg_2':
          'এই ত্রৈমাসিকে সাড়া দেওয়ার সময় উন্নত করতে ড্রেনেজ ও রাস্তা রক্ষণাবেক্ষণ টিকিট এলাকা অনুযায়ী ম্যাপ করা হয়েছে।',
      'local_msg_3':
          'ডুপ্লিকেট অভিযোগ কমাতে সিটিজেন হেল্পডেস্ক এখন রিয়েল-টাইম ইস্যু রাউটিং সমর্থন করে।',
      'local_msg_4':
          'নাইট সেফটি লাইটিং প্রোগ্রাম দ্বিতীয় ধাপে প্রবেশ করেছে; প্রেডিক্টিভ মনিটরিং সক্রিয় হয়েছে।',
      'local_msg_5':
          'সব এলাকায় স্যানিটেশন অনুরোধের জন্য ১০০ শতাংশ জিওট্যাগ যাচাই সম্পন্ন হয়েছে।',
      'state_msg_1':
          'দ্রুত যাচাইয়ের মাধ্যমে রাজ্য স্কলারশিপ অনবোর্ডিং গুরুত্বপূর্ণ মাইলস্টোন অতিক্রম করেছে।',
      'state_msg_2':
          'শিক্ষা, স্বাস্থ্য ও সাড়া দেওয়ার পারফরম্যান্সের জন্য জেলা KPI এখন সাপ্তাহিক প্রকাশিত হয়।',
      'state_msg_3':
          'বিভাগীয় রিপোর্টিং ও গভর্ন্যান্স অডিট উন্নত করতে স্টেট সার্ভিস রেজিস্ট্রি মানসম্মত করা হয়েছে।',
      'state_msg_4':
          'নতুন এসকেলেশন ফ্রেমওয়ার্ক পাইলট জেলাগুলোতে গুরুতর সমস্যা সমাধানের সময় ৩০ শতাংশের বেশি কমিয়েছে।',
      'state_msg_5':
          'সেবা ধারাবাহিকতা ও পারফরম্যান্স ট্র্যাকিংয়ের জন্য একীভূত স্টেট কমান্ড ভিউ চালু করা হয়েছে।',
      'national_msg_1':
          'জাতীয় নীতি স্প্রিন্ট মানসম্মত ডিজিটাল সেবা প্যাটার্ন দিয়েছে, যা এখন বিভিন্ন বিভাগে চালু হচ্ছে।',
      'national_msg_2':
          'ক্রস-রিজিয়ন কমান্ড ওয়ার্কফ্লো এখন রিয়েল-টাইম এসকেলেশন এবং SLAসহ সক্রিয়।',
      'national_msg_3':
          'জাতীয় ট্রান্সফরমেশন ফ্রেমওয়ার্কে ত্রৈমাসিক প্রস্তুতি স্কোরিং অন্তর্ভুক্ত করা হয়েছে।',
      'national_msg_4':
          'পাবলিক সার্ভিস আধুনিকীকরণ রোডম্যাপ KPI জবাবদিহিতাসহ বাস্তবায়ন পর্যায়ে প্রবেশ করেছে।',
      'national_msg_5':
          'ডেটা গভর্ন্যান্স, রিপোর্টিং ক্যাডেন্স এবং স্থিতিস্থাপকতার জন্য আন্তঃরাজ্য অপারেটিং মডেল এখন সমন্বিত।',
    },
  };

  static String translate(String key, {String language = 'English'}) {
    final translations = _strings[language];
    return translations?[key] ?? _strings['English']![key] ?? key;
  }
}
